application/flask_blog/models/entries.py
from flask_blog import db
from datetime import datetime

class Entry(db.Model):
    __tablename__ = 'entries'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), unique=True)
    text = db.Column(db.Text)
    created_at = db.Column(db.DateTime)

    def __init__(self, title=None, text=None):
        self.title = title
        self.text = text
        self.created_at = datetime.utcnow()

    def __repr__(self):
        return '<Entry id:{} title:{} text:{}>'.format(self.id, self.title, self.text)

application/flask_blog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('flask_blog.config')

db = SQLAlchemy(app)

from flask_blog.views.entries import entry

app.register_blueprint(entry, url_prefix='/users')

from flask_blog.views import views

application/flask_blog/views/entries.py
from flask import request, redirect, url_for, render_template, flash, session
from flask_blog import app
from flask_blog.models.entries import Entry
from flask_blog import db
from flask_blog.views.views import login_required
from flask import Blueprint

entry = Blueprint('entry', __name__)

@entry.route('/')
@login_required
def show_entries():
    entries = Entry.query.order_by(Entry.id.desc()).all()
    return render_template('entries/index.html', entries=entries)

@entry.route('/entries/new', methods=['GET'])
@login_required
def new_entry():
    return render_template('entries/new.html')

@entry.route('/entries/<int:id>', methods=['GET'])
@login_required
def show_entry(id):
    entry = Entry.query.get(id)
    return render_template('entries/show.html', entry=entry)

@entry.route('/entries/<int:id>/edit', methods=['GET'])
@login_required
def edit_entry(id):
    entry = Entry.query.get(id)
    return render_template('entries/edit.html', entry=entry)

@entry.route('/entries/<int:id>/update', methods=['POST'])
@login_required
def update_entry(id):
    entry = Entry.query.get(id)
    entry.title = request.form['title']
    entry.text = request.form['text']
    db.session.merge(entry)
    db.session.commit()
    flash('update article')
    return redirect(url_for('entry.show_entries'))

@entry.route('/entries/<int:id>/delete', methods=['POST'])
@login_required
def delete_entry(id):
    entry = Entry.query.get(id)
    db.session.delete(entry)
    db.session.commit()
    flash('Article has deleted.')
    return redirect(url_for('entry.show_entries'))


@entry.route('/entries', methods=['POST'])
@login_required
def add_entry():
    entry = Entry(
        title = request.form['title'],
        text = request.form['text']
    )
    db.session.add(entry)
    db.session.commit()
    flash('New post has created.')
    return redirect(url_for('entry.show_entries'))

application/flask_blog/views/views.py
from flask import request, redirect, url_for, render_template, flash, session
from flask_blog import app
from functools import wraps

def login_required(view):
    @wraps(view)
    def inner(*args, **kwargs):
        if not session.get('logged_in'):
            return redirect(url_for('login'))
        return view(*args, **kwargs)
    return inner

@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        if request.form['username'] != app.config['USERNAME']:
            flash("Wrong username")
        elif request.form['password'] != app.config['PASSWORD']:
            flash("Wrong password")
        else:
            session['logged_in'] = True
            flash("login")
            return redirect('/')
    return render_template("login.html")

@app.route('/logout')
def logout():
    session.pop('logged_in', None)
    flash('logged out')
    return redirect(url_for('entry.show_entries'))

@app.errorhandler(404)
def non_existant_route(error):
    return redirect(url_for('login'))

application/flask_blog/templates/entries/edit.html
{% extends "layout.html" %}
{% block body %}

<form action="{{ url_for('entry.update_entry', id=entry.id) }}" method="post" class="add-entry">
    <div class="form-group">
        <label for="InputTitle">Title</label>
        <input type="text" class="form-control" id="InputTitle" name="title" value="{{ entry.title }}">
    </div>
    <div class="form-group">
        <label for="InputText">Text</label>
        <textarea class="form-control" id="InputText" name="text" rows="3">{{ entry.text | safe }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>

{% endblock %}

application/flask_blog/templates/entries/index.html
{% extends "layout.html" %}
{% block body %}
<ul class="list-group list-group-flush">

{% for entry in entries %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ entry.title }}</h5>
            <a href="{{ url_for('entry.show_entry', id=entry.id) }}" class="card-link">Read more...</a>
        </div>
    </div>
{% else %}
    No posts.
{% endfor %}
</ul>
{% endblock %}

application/flask_blog/templates/entries/new.html
{% extends "layout.html" %}
{% block body %}

<form action="{{ url_for('entry.add_entry') }}" method="post" class="add-entry">
    <div class="form-group">
        <label for="InputTitle">
            Title
        </label>
        <input type="text" class="form-control" id="InputTitle" name="title">
    </div>
    <div class="form-group">
        <label for="InputText">
            Text
        </label>
        <textarea class="form-control" id="InputText" name="text" rosw="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

application/flask_blog/templates/entries/show.html
{% extends "layout.html" %}
{% block body %}

<h2>{{ entry.title }}</h2>
{{ entry.text | safe }}

Posted at: {{ entry.created_at }}

<div class="btn-group">
    <form action="{{ url_for('entry.edit_entry', id=entry.id) }}" method="GET">
        <button type="submit" class="btn btn-secondary">Edit</button>
    </form>
    <form action="{{ url_for('entry.delete_entry', id=entry.id) }}" method="POST">
        <button type="submit" class="btn btn-danger" style="margin-left: 5px">Delete</button>
    </form>
</div>

{% endblock %}

application/flask_blog/templates/layout.html
<!doctype html>
<html>
<head>
<title>Flask Blog</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Flask-book</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                    {% if not session.logged_in %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('login') }}">Login</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('entry.new_entry') }}">New Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('logout') }}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info" role="alert">
            {{ message }}
        </div>
        {% endfor %}

        <div class="blog-body">
            {% block body %}{% endblock %}
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

application/flask_blog/templates/login.html
{% extends "layout.html" %}
{% block body %}
<form action="{{ url_for('login') }}" method="post">
    <div class="form-group">
        <label for="InputTitle">User name</label>
        <input type="text" class="form-control" id="InputTitle" name="username">
    </div>
    <div class="form-group">
        <label for="InputPassword">Password</label>
        <input type="password" class="form-control" id="InputPassword" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}